### ISSUE TITLE
All Day Events

### ISSUE THREAD

**Issue by kingargyle** [alamkanak/Android-Week-View#101]
Is there a way to represent events as being All Day Events.

We have a lot of events that have a Start Date but no End Date time.  These are typically All Day events.  They have no start times just a start date.   Right now if I include these events they all show up at the same hour, and overlap each other.

I tried setting overlapping attribute but that didn't affect anything.

**Comment by alamkanak** [comment]
Currently, all day events are not possible. But it will be a good idea to add this in the future.

**Comment by lolobosse** [comment]
I'd like to make this feature. @alamkanak and @caske33 do you have a particular wish concerning the design of this feature?

**Comment by caske33** [comment]
My wishes would be:
- on top of the screen (preferably always visible)
- height of these events should be configurable through a setting
- preferably also a clear distinction between all-day events and normal events (a line or something).

**Comment by alamkanak** [comment]
I agree with @caske33. Additionally, one would want to
- configuree the separator height and color
- set the maximum number of visible all-day events

**Comment by lolobosse** [comment]
:construction: :construction: :construction: :construction_worker: Coding... :construction_worker: :construction: :construction: :construction: 

Hey guys,

I thought a lot about this feature and I have one question and one potential issue:

**The question:**
How do you want the `allDayEvent` to handle `onClick` or `onLongClick`? Do you want it to have its special listener or do you expect the same listener returning this `AllDayWeekViewEvent` (or a `WeekViewEvent` with a boolean) ? If you'd like the second option, it could introduce quite a lot of changes because we won't be able to use the `getTimeFromPoint`method.

**The potential issue:**
We could have an issue because the design of the library does not allow you to have different header heights per day. It means that, considering we'd have a 3 days view, one day has 2 `allDayEvent`, another has only one and, the last one, none. Then, there are two approaches, the first is to keep the library as it is and to add the `allDayEvent` to the header part (or to create a second header part for this kind of event) and then, as soon as there is a `allDayEvent` in the visible view, we show it where we have to and we add an offset to the views where there is no `allDayEvent` (or not so many `allDayEvent`). I personally find it not so cool because it could use space for nothing (on the views where there is no/less `allDayEvent`).

The other approach would be to design a floating event which would float on the top of the "nomal" events but will "respect" the headers of the view. I prefer this solution because it could also provide an easy solution to the answer of my **question** (whatever answer you choose).

To summary this long and boring text: do I put it in the header or as a floating event ? How do I design the click listener of the `allDayEvent`? :smile:

**Comment by caske33** [comment]
First of all, I love your use of emoji's and clear comments :smile: Keep up the good work :+1: 

1. Personally, I think there's gonna be a lot of rewrite of code anyway. Because all the y-coordinates, currently use a sum of the other parts of the view (`y - mCurrentOrigin.y - mHeaderTextHeight - mHeaderRowPadding * 2 - mTimeTextHeight/2 - mHeaderMarginBottom`) (maybe a method for this could also be useful? Especially since the headers are gonna be flexible now).
But I think externally, the same listener should be used. How you handle it internally, is another point and I would say, do whatever is most maintainable.
2. Most calendars have a fixed space for all-day events. Personally, I think that will be the most clear way to represent it (from an usability point of view). But I think floating could also work, although you'll have to make sure that if an event occurs at 00:00, it should be rendered properly with respect to the all-day event.

**Comment by snacky6** [comment]
I think a fixed space is the best way to represent it too! But are you still working on this enhancement? Because I would need it for a project I'm working on. Thanks :smile:

**Comment by lolobosse** [comment]
Yeah, I'm also building up my own startup yet so do not have that much time but yes, that's always one of my midterm target.

**Comment by snacky6** [comment]
Alright! Good luck for your startup, I hope everything is going well.

**Comment by 10pu4** [comment]
Any updates on this improvement?

**Comment by lolobosse** [comment]
Nope, not at all :cry:

**Comment by wwahmed** [comment]
My suggestion regarding the all day view would be to treat it just like an 'hour' block. Instead of a header, an extra hour block can be created at the top (imagine hour -1 to 0), and all all day events for that day would be drawn in side that hour block. 

All behavior for the events would be the same as if there were multiple events in the same hour window. They would appear next to each other, dividing horizontal space amongst themselves.

All the call backs for these events would be no different that other call backs.

**Comment by caske33** [comment]
@wwahmed I think that might be a good idea, but there are some other complications. E.g. this all day block has to be always visible, even if the top hours are not visible. 

But feel free to take a shot at it. The library is rather simple so it's easy to dive into it.

**Comment by nrazon** [comment]
This feature is really needed and important. 
I think no one yet succeed implementing this feature?

**Comment by lolobosse** [comment]
Nope, as I said, I started but I didn't have it properly done and my approach is not even good. If you want it, start it from scratch.
Nevertheless, I'll be happy to review it! :smile: :pray: :clap:

**Comment by IvoNedev** [comment]
So it turned out "All Day" event is pretty simple to implement, much in the same way a specific range of hours to display is...

The later is explained [here on SO](https://stackoverflow.com/questions/35944431/filter-specific-range-of-hours-to-show-in-alamkanak-android-week-view/49979071#49979071)

Before looping trough and displaying the hours digits, I hard code an "All Day" string at index 0, and then loop from 1 to 13 (to display 07:00 - 19:00 hours in my specific case)

I just need to set an event's start hour to be an hour before 7 for it to go into the "All Day" events
