### ISSUE TITLE
New feature: now indicator

### ISSUE THREAD

**Issue by piotrwojtowicz** [alamkanak/Android-Week-View#117]
It would be nice to have possibility to see some indicator for current hour of current day, i.e. some horizontal line of some color.

**Comment by caske33** [comment]
#67 implements this already

**Comment by lolobosse** [comment]
#118 do what you want, it's the same as #67 but only with the line and based on the newest version of master.

**Comment by piotrwojtowicz** [comment]
thank you guys :) 

One side question, currently I am working with Android-Week-View in my app developed in Android Studio by using:

compile 'com.github.alamkanak:android-week-view:1.2.1'

in build.gradle's dependencies. Is there some manual how to use other ppl modifications (forks) from GitHub? Can I use them in similiar way as master or should I download whole project code (i.e. caske33's modifications) and build it together with my app? I know it's noob question, but I really can't find good answer, there are mainly articles about syncing my own project with GitHub. Any advice would be appreciated, even google search phrases would be ok ;)

**Comment by lolobosse** [comment]
It's not a noob question, it's not that easy:

What you need to do is to take the URL of the fork you want (the .git URL of course) and add it to your remotes. Then fetch it. If you have chance (if you take my fork and you didn't work on the original one for example) you should have no conflict and you'll be able to merge my changes in your code. But it could be much more complicated: if you take the #67 as @caske33 proposed, you'll have a bunch of merge conflicts to solve (I tried it because it would have been much easier for me, instead of recoding the same functionality) and that's why I created another push request because mine is able to merge direct with the latest version of the master.

But if you want to have @caske33 fork, what you could is just fork his fork and then you'll be sure to have all of his changes :smile: but do not forget, I know that using the `compile 'com.github.alamkanak:android-week-view:1.2.1'`is easier but you cannot modify the source code of the library after that; that's why we clone the repository.

**Comment by caske33** [comment]
I've described it here too: https://github.com/alamkanak/Android-Week-View/issues/54#issuecomment-72930730

But instead of merging my PR, you'll probably want to merge @lolobosse's branch, if the now-indicator is the only new functionality you need.

**Comment by piotrwojtowicz** [comment]
Thank you guys for good description, I will try both methods, to learn something new which might be useful in future :)

**Comment by obaslan** [comment]
Thanks a lot for the nowline @caske33  and @lolobosse . I am currently using #118 . When I scroll up. the NowHourLine scrolls over the HeaderText and the line is in front of them. What I desire is to have it go to the back of the header just like the TimeTexts. Are you having a similar issue?

**Comment by caske33** [comment]
@obaslan can you try the develop branch from this repo?

**Comment by obaslan** [comment]
@caske33  would you be able to specify which commit you mean exactly?

**Comment by caske33** [comment]
https://github.com/alamkanak/Android-Week-View/commit/3396a814584959a8e5ef6e36cf7a8ba254274e6f should work normally. (The merge happened earlier on, but it's best to test that version). You have to enable the newColoring (or something like that) attribute though.

**Comment by marunjar** [comment]
hi @obaslan 
can you also check your colors used for header?
if some of them are transparent it can be possible that the text is drawn over text

**Comment by obaslan** [comment]
@marunjar  That did not solve the problem.
@caske33 The commit you shared has changes to the drawEventTitle method. Will that help with the Header being behind the nowHourLine?

**Comment by caske33** [comment]
@obaslan I just referenced the latest commit. That commit had nothing to do with it. 

And can you provide more information about what exactly goes wrong?

**Comment by obaslan** [comment]
Thanks @caske33  Problem solved. I was drawing the header before the NowLine, So NowLine was coming forward.

**Comment by caske33** [comment]
1.2.4 has a nowIndicator.
