### ISSUE TITLE
Use this library in Eclipse

### ISSUE THREAD

**Issue by ajinkyapote1** [alamkanak/Android-Week-View#121]
First thanks for such superb library for calendar view.
I want use this in Eclipse but without gradle/maven, so how can i use it?
and if i can't use it without gradle/maven, how can integrate gradle or maven into my eclipse.

Thanks in advance.

**Comment by lolobosse** [comment]
Theoritically, you could include a jar that you compile from Android
Studio. I'll try to compile one today and put it in my fork.

However, there is another solution: the WeekView is just composed of two
classes so you could just copy paste it and import the support library it's
using. Then you'll need to modify your attrs.xml file. This solution is
maybe the quickest and good to give a try but for a long term use, I'd
recommend the first method because you can easily update your lib by
changing the jar.

Have fun :smile:
Am 27.04.2015 8:21 vorm. schrieb "ajinkyapote1" <notifications@github.com>:

**Comment by ajinkyapote1** [comment]
Thanks for the suggestion, but from where can i include that jar? i have never used Android Studio.
I am using Eclipse.

**Comment by lolobosse** [comment]
You include in your build path like any other not online dependencies. But the jar is not there currently, not that I know. I’ve to compile one (but currently at the University, cannot do it right now)

Maybe have a look in other popular forks and with a bit of luck, you’ll be able to find one.

**Comment by ajinkyapote1** [comment]
Did you compile it?

**Comment by ajinkyapote1** [comment]
Hi,
    Did you compile the jar from Android studio?
Could you please help me to use this library in eclipse ASAP?

**Comment by lolobosse** [comment]
I think it'll a bit more complicated than what I thought so I would follow this tutorial: http://stackoverflow.com/a/20806308/2545832

**Comment by ajinkyapote1** [comment]
I follow the steps in that tutorial, it worked in eclipse.
Thank you very much... you saved me +1:
