### ISSUE TITLE
Ellipsize bug (text is to long in case of some long words in the middle of the event text)

### ISSUE THREAD

**Issue by caske33** [alamkanak/Android-Week-View#206]
Sometimes the ellipsize in `drawEventTitle()` doesn't work because it's doesn't take into consideration that some space might be lost horizontally when a long words starts at the next line. If you look very closely in the screenshot, below the green rectangle, there is still white text. 

![screenshot_2015-10-29-21-42-41](https://cloud.githubusercontent.com/assets/896093/10831472/140e59ca-7e86-11e5-99aa-ba21c31cee2b.png)

@marunjar @lolobosse @alamkanak do any of you know a way to fix this bug?

**Comment by marunjar** [comment]
hi, i think it just needs some more checking of text  height after ellipsizing and if it doesn't fit the event rect, some lines must be removed until it fits again.

i just tried this and it seems to work, there also shouldn't be much loops.  
But i don't have much data for testing 'cause this only happens every once and a while.
Maybe you can give it a try?
  
    private void drawEventTitle(WeekViewEvent event, RectF rect, Canvas canvas, float originalTop, float originalLeft) {
        if (rect.right - rect.left - mEventPadding * 2 < 0) return;
        if (rect.bottom - rect.top - mEventPadding * 2 < 0) return;

        SpannableStringBuilder bob = new SpannableStringBuilder();
        if (event.getName() != null) {
            bob.append(event.getName());
            bob.setSpan(new StyleSpan(android.graphics.Typeface.BOLD),0,bob.length(),0);
            bob.append(' ');
        }
        if (event.getLocation() != null) {
            bob.append(event.getLocation());
        }

        int availableHeight = (int) (rect.bottom - originalTop - mEventPadding * 2);
        int availableWidth = (int) (rect.right - originalLeft - mEventPadding * 2);

        // Get text dimensions
        StaticLayout textLayout = new StaticLayout(bob, mEventTextPaint, availableWidth, Layout.Alignment.ALIGN_NORMAL, 1.0f, 0.0f, false);

        int lineHeight = textLayout.getHeight() / textLayout.getLineCount();

        if (availableHeight >= lineHeight) {
            // calculate available lines
            int availableLineCount = availableHeight / lineHeight;
            do {
                // ellipsize text to fit into event rect
                textLayout = new StaticLayout(TextUtils.ellipsize(bob, mEventTextPaint, availableLineCount * availableWidth, TextUtils.TruncateAt.END), mEventTextPaint, (int) (rect.right - originalLeft - mEventPadding * 2), Layout.Alignment.ALIGN_NORMAL, 1.0f, 0.0f, false);
                // reduce line count
                availableLineCount--;
                // and repeat until text is short enough
            } while (textLayout.getHeight() > availableHeight);

            // Draw text
            canvas.save();
            canvas.translate(originalLeft + mEventPadding, originalTop + mEventPadding);
            textLayout.draw(canvas);
            canvas.restore();
        }
    }

another possiblity would  be the StaticLayout.Builder [1]. It's only available for api 23, but it has a lot of properties to improve layout (maybe we should update the api version to 23 and use the loop version only as fallback for older devices)

So instead of the ugly loop you can use this:

            textLayout = StaticLayout.Builder.obtain(bob, 0, bob.length(), mEventTextPaint, availableWidth)
                    .setMaxLines(availableLineCount)
                    .setEllipsize(TextUtils.TruncateAt.END)
                    .setBreakStrategy(BREAK_STRATEGY_BALANCED)
                    .build();


[1] http://developer.android.com/reference/android/text/StaticLayout.Builder.html)

**Comment by caske33** [comment]
Thx @marunjar!
