### ISSUE TITLE
7+ visible days issue

### ISSUE THREAD

**Issue by lucacastenetto** [alamkanak/Android-Week-View#267]
Hi,

I've found a bug if I select 7 or more visible days before the view is drawn for the first time, it shows me always the week before the one I need.
I spotted that is caused by the 7 days added into the difference calculation from today and the first day of the week (`Line 540 of WeekView`). So for example if today is tuesday and the first day is monday the difference is 8 and the first day shown is 8 days ago.

I removed the added days in my branch and can make a PR if needed. 

If there was a particular reason for that days added please tell me :smile:

**Comment by entropitor** [comment]
I think @alamkanak added this to have always shown a "regular week" starting at the first day of the week.

But I think it's a bad semantics for the default value and I'm personally pro having an attribute `showFirstDayOfWeekFirst`, default false. If the value is true, have the current behaviour and otherwise the behaviour as for less than 7 days.

A PR would be wonderfull. 

@lolobosse @marunjar @alamkanak What do you think of the idea I proposed above?

**Comment by marunjar** [comment]
I'm pro mShowFirstDayOfWeekFirst = false so it would have the same behaviour like < 7 days.

In my cases i'm not really interested in what happened in the past and start only with showing events from today.

**Comment by entropitor** [comment]
Closed by #269 .
