### ISSUE TITLE
how to using SwipeRefreshLayout on WeekView?

### ISSUE THREAD

**Issue by alandwiprasetyo** [alamkanak/Android-Week-View#284]
I want refresh data event on Weekview using SwipeRefreshLayout. how to step refresh data using SwipeRefreshLayout?

**Comment by entropitor** [comment]
I'm gonna close this because it's not really an bug in the library, for which github issues serves.

Personally, I don't think it's possible / a good idea to have pull to refresh together with the weekview because the pull is the same behaviour as the scrolling down. It might be possible, but I'd not advise it.

**Comment by encodeering** [comment]
@caske33 Maybe you could expose a scroll listener (or modify the existing), that is capable to determine, if the scrollbar is positioned at the _top_ or _bottom_ of the view. That would leave the decision to add a _swipe-and-refresh_ behaviour to the developer/application

I'd like to add the same behaviour than @alandwiprasetyo and would argue, that other nestable vertical-scrollable widgets (e.g. lists) can be used in the same way

Thanks in advance
