### ISSUE TITLE
Screen bug when i scroll weekView

### ISSUE THREAD

**Issue by sebasme** [alamkanak/Android-Week-View#385]
Hello everybody,
I use the Android WeekView library for my project and when I scroll the view I have this bug.
Someone could explain me how to fix this problem.
Thanks in advance.

PS: Super Library and beautiful work
![bugweekview](https://cloud.githubusercontent.com/assets/13061292/20055879/a4e9cb94-a4e3-11e6-9559-d0c330278c9a.png)

**Comment by sebasme** [comment]
Somebody can help me please !!!!!

Thanks in advance.

**Comment by cgillions** [comment]
I am facing the same issue. When I scroll down on the fragment, the WeekView goes in front of the toolbar and produces the same kind of error you described.

**Comment by cgillions** [comment]
It happens consistently. I have the WeekView in a scroll view. When the top of the week view reaches the toolbar, it goes on top of it. The toolbar buttons are still active and in the right place. All other views in the ScrollView go under the toolbar.

**Comment by cgillions** [comment]
See also - #404

**Comment by sebasme** [comment]
Ok , thanks.
So , I'm close this issue

**Comment by cgillions** [comment]
Are you facing the issue in a ScrollView as well?

**Comment by minhanhhere** [comment]
Hi, @cgillions @sebasme 

I found out that this bug occured in API 21, 22 when the WeekView is in a ScrollView.
To make a workaround & resolve this issue, I **remove** all clipRect (in WeekView.java) that look like the following:

```java
canvas.clipRect(left, top, width, heigh, Region.Op.REPLACE);
```

Just search all Op.REPLACE in the code (exactly 4 found) and remove them, then everything works perfectly again.

Canvas.clipRect is used for performance improvement ([read here](https://medium.com/google-developers/draw-what-you-see-and-clip-the-e11-out-of-the-rest-6df58c47873e#.k9n1x8up8)). So in this case, there should be no problem when remove them. Because everything on the canvas is calculated perfectly.

I guess API 21, 22 may have problem when apply the clipRect with flag `Op.REPLACE`. API 23 is free of this bug. For another workaround, I think a check for the API version before calling **clipRect** may also works.

**Comment by akilaselvi** [comment]
I am facing same issues, inside scroll view i used  "com.alamkanak.weekview.WeekView",  i want to remove this line canvas.clipRect(mViewPortHandler.getContentRect()) ?

**Comment by Bhupendraparas** [comment]
i am facing same issue also if any one know about that please let me know 
week view scrolling not working ,and also try to disable scroll on the touch on week view but still not working
