### ISSUE TITLE
How to delete an event

### ISSUE THREAD

**Issue by preyesm** [alamkanak/Android-Week-View#396]
Is there a way to delete the events added to the weekView.

Saw how to do it in one of the closed issues.Thanks

**Comment by QArtur99** [comment]
@preyesm buddy how to do it ? i have the same problem I'm using fragments and i can just delete events which i added while ago but if sth was before i cant remove it immediately

**Comment by QArtur99** [comment]
I got it Thanks

**Comment by TroniPM** [comment]
@QArtur99 can you please tell me how you did this? Thanks.

**Comment by QArtur99** [comment]
When youre loading your weekView you have to create list for all events then onMonthChange you just selecting events for 1 month so when you want remove event you need remove it from your list and than call onMonthChange for this 1 month where you changed sth in order to select again items for this month

**Comment by TroniPM** [comment]
Well, i was removing the weekevent from this list and than calling "getWeekView().notifyDatasetChanged();", but i couln't make the weekview redraw the calendar without this event... This is awkward.

**Comment by QArtur99** [comment]
I'm doing sth like that

` private List<WeekViewEvent> events;`
`events.remove(event);`
`onMonthChange(2017,` 1);`

`mWeekView.notifyDatasetChanged();`
