### ISSUE TITLE
How to use scroll-listner tree from caske33

### ISSUE THREAD

**Issue by Shajeel-Afzal** [alamkanak/Android-Week-View#71]
Hi!

I want to add day change listener, i see that it is already done in the https://github.com/caske33/Android-Week-View/tree/scroll-listener. 

But i want to know that you to use it, should i wait for alamkanak/Android-Week-View to merge that branch?

Thanks.

**Comment by caske33** [comment]
@alamkanak is a bit sick right now (https://github.com/alamkanak/Android-Week-View/issues/65#issuecomment-72555453) but when he is back, if a PR ready for him: #50. If he merges that, the code will be released via maven.

If you want to use it right now already, you should checkout my description on how to do that here: https://github.com/alamkanak/Android-Week-View/issues/54#issuecomment-72930730. This is however just a temporary option, until @alamkanak is back.

I hope that answers your question. Otherwise, just ask! :smile:

**Comment by Shajeel-Afzal** [comment]
Get well soon @alamkanak.

**Comment by alamkanak** [comment]
Fixed in v1.2.3
